### ISSUE TITLE
New navigation stack

### ISSUE THREAD

**Issue by Knurenko** [Knurenko/learning-react-by-practice#6]
New navigation stack should contain 3 screens. "Product list", "Add new product" and a "Product info"
Inside of navigation component file you should create an object with route names like
```
const routes = {
SCREEN_PRODUCT_LIST: "product list",
SCREEN_ADD_NEW_PRODUCT: "add new product",
SCREEN_PRODUCT_INFO: "show product info"
}
export routes

**Comment by Knurenko** [comment]
Then later just import it and use in any other file.

**Comment by Nykaloff** [comment]
complete #9
